### ISSUE TITLE
[backend] Create API endpoints for managing webhook URLs

### ISSUE THREAD

**Issue by pandafy** [MLH-Fellowship/pod_1.0.2_moropy#23]
Create following endpoints for managing webhook URLs:

### ```GET /channel/{channel_id}/ ```

Response:
```
{
    "channel_id": <int:id>,
    "webhook_url": <string:url>
}
```

### ``` POST /channel/{channel_id}/```
```
{
    "webhook_url": <string:url>
}
```

**EDIT:** Should be done after https://github.com/rish07/pod_1.0.2_moropy/issues/24

**Comment by rish07** [comment]
Closed in #35
