### ISSUE TITLE
[backend] Add field in user schema for storing webhook URLs

### ISSUE THREAD

**Issue by pandafy** [MLH-Fellowship/pod_1.0.2_moropy#26]
Update user schema to have array of webhook URLs stored in them
It will look something like this

```
{
    'users': {
        'user_id1':{
            ...
            'webhookUrls': ['url1', 'url2', 'url3'],
            ...
        },
        'user_id2':{
            ...
            'webhookUrls': ['url1', 'url2', 'url4'],
            ...
        },
    }
}
```

This is a quick dirty fix for the problems we are facing currently for sending messages to user channels. 
Opened #27 for future reference and added points to improve.

**Comment by rish07** [comment]
closed in #35
